# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/test.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/test.proto',
  package='test',
  syntax='proto3',
  serialized_pb=_b('\n\x10proto/test.proto\x12\x04test\"#\n\x07TestReq\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"#\n\x07TestRsp\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\rb\x06proto3')
)




_TESTREQ = _descriptor.Descriptor(
  name='TestReq',
  full_name='test.TestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.TestReq.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='test.TestReq.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=61,
)


_TESTRSP = _descriptor.Descriptor(
  name='TestRsp',
  full_name='test.TestRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='test.TestRsp.id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='test.TestRsp.name', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=98,
)

DESCRIPTOR.message_types_by_name['TestReq'] = _TESTREQ
DESCRIPTOR.message_types_by_name['TestRsp'] = _TESTRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestReq = _reflection.GeneratedProtocolMessageType('TestReq', (_message.Message,), dict(
  DESCRIPTOR = _TESTREQ,
  __module__ = 'proto.test_pb2'
  # @@protoc_insertion_point(class_scope:test.TestReq)
  ))
_sym_db.RegisterMessage(TestReq)

TestRsp = _reflection.GeneratedProtocolMessageType('TestRsp', (_message.Message,), dict(
  DESCRIPTOR = _TESTRSP,
  __module__ = 'proto.test_pb2'
  # @@protoc_insertion_point(class_scope:test.TestRsp)
  ))
_sym_db.RegisterMessage(TestRsp)


# @@protoc_insertion_point(module_scope)
